package basic.ch05_entity_mapping.domain.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Entity @Table(name = "identity_example_entity")
@Getter @Setter @NoArgsConstructor
public class GeneratedValueIdentityExampleEntity {

    /** @GeneratedValue(strategy = GenerationType.IDENTITY)
     * - 기본 키 생성을 DB에 위임
     * - JPA는 보통 트랜잭션 커밋 시점에 INSERT SQL 실행
     * - AUTO_INCREMENT는 DB에 INSERT SQL 실행 후 ID값을 알 수 있음
     * - IDENTITY 전략은 persist 대상 객체를 영속성 컨텍스트에 캐싱 하기 위해 필요한 ID값을 조회하기 위해
     *   EntityManager.persist() 시점에 즉시 INSERT SQL을 실행하고 DB에서 식별자를 조회하여 영속성 컨텍스트에 캐싱
     * - 주로 MySQL, PostgreSQL, SQL Server, DB2에서 사용
     *    - EX) MySQL의 AUTO_INCREMENT
     *
     * - Create DDL Example
     *   create table GeneratedValueIdentityExampleEntity (
     *       id bigint generated by default as identity,
     *       name varchar(255),
     *       primary key (id)
     *   )
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String value;
}